import { Award, Download, Eye, History, ShieldAlert, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'

import { DonutChart } from '@/components/charts'
import { DataTable, type Column } from '@/components/common/DataTable'
import { KpiCard, KpiStrip } from '@/components/common/KpiCard'
import { StatusPill } from '@/components/common/StatusPill'
import { Banner, Button, Card } from '@/components/common/primitives'
import { ROUTES } from '@/constants/routes'
import { useAsync } from '@/hooks/useAsync'
import { useAuth } from '@/hooks/useAuth'
import { api, seed } from '@/mock/api'
import type { MeritList } from '@/types'

export default function MeritDashboard() {
  const { data, isLoading } = useAsync(() => api.meritLists(), 'meritLists')
  const { can } = useAuth()
  const lists = data ?? []

  const columns: Column<MeritList>[] = [
    {
      key: 'exam',
      header: 'Examination',
      accessor: (row) => row.examName,
      sortable: true,
      render: (row) => (
        <Link
          to={ROUTES.EA_MERIT_LIST(row.id)}
          className="font-medium text-navy-700 hover:underline"
        >
          {row.examName}
        </Link>
      ),
    },
    { key: 'post', header: 'Post / Category', accessor: (row) => row.post },
    {
      key: 'version',
      header: 'Version',
      accessor: (row) => row.version,
      sortable: true,
      render: (row) => (
        <span className="inline-flex items-center gap-1.5">
          v{row.version}
          {row.version > 1 && (
            <span className="text-[11px] text-grey-600" title="Earlier versions are retained and comparable">
              <History className="inline size-3" /> {row.version - 1} superseded
            </span>
          )}
        </span>
      ),
    },
    {
      key: 'size',
      header: 'List size',
      accessor: (row) => row.size,
      sortable: true,
      className: 'text-right',
      headerClassName: 'text-right',
    },
    {
      key: 'appeared',
      header: 'Appeared',
      accessor: (row) => row.appeared,
      className: 'text-right',
      headerClassName: 'text-right',
      render: (row) => row.appeared.toLocaleString('en-IN'),
    },
    { key: 'generated', header: 'Generated on', accessor: (row) => row.generatedOn, sortable: true },
    { key: 'by', header: 'Generated by', accessor: (row) => row.generatedBy },
    { key: 'status', header: 'Status', render: (row) => <StatusPill status={row.status} /> },
    {
      key: 'approval',
      header: 'Approval',
      render: (row) =>
        row.approved ? (
          <span className="text-[12px] text-green-600">Signed — {row.signedBy}</span>
        ) : (
          <span className="text-[12px] text-amber-500">Awaiting approval</span>
        ),
    },
  ]

  return (
    <div className="page">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="page-title">Merit Dashboard</h1>
          <p className="mt-0.5 text-[13px] text-grey-600">
            Merit lists across examinations, with their version history and approval state.
          </p>
        </div>
        {can('merit.generate') && (
          <Link to={ROUTES.EA_MERIT_GENERATE}>
            <Button>
              <Award className="size-4" />
              Generate Merit
            </Button>
          </Link>
        )}
      </div>

      <Banner tone="danger" icon={<ShieldAlert className="size-4" />} title="Confidential — not for public display">
        Merit lists are viewable only by concerned officials. Every view and download is logged
        against your Employee ID and exports are watermarked with it.
      </Banner>

      <KpiStrip>
        <KpiCard icon={<Award className="size-5" />} label="Merit lists" value={lists.length} tone="purple" />
        <KpiCard
          icon={<Trophy className="size-5" />}
          label="Approved & signed"
          value={lists.filter((list) => list.approved).length}
          tone="green"
        />
        <KpiCard
          icon={<History className="size-5" />}
          label="Awaiting approval"
          value={lists.filter((list) => !list.approved).length}
          tone="amber"
        />
        <KpiCard
          icon={<Trophy className="size-5" />}
          label="Selection lists"
          value={seed.selectionLists.length}
          tone="blue"
        />
      </KpiStrip>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]">
        <Card title="Merit lists">
          <DataTable
            rows={lists}
            columns={columns}
            rowKey={(row) => row.id}
            isLoading={isLoading}
            searchPlaceholder="Search by examination or post"
            searchFields={(row) => `${row.examName} ${row.post}`}
            filters={[
              {
                key: 'status',
                label: 'Status',
                options: ['Completed', 'Under Moderation', 'In Progress'],
                match: (row, value) => row.status === value,
              },
            ]}
            emptyTitle="No merit lists yet"
            emptyDescription="Generate a merit list once evaluation is complete and consolidated."
          />
        </Card>

        <div className="space-y-4">
          <Card title="Category Wise Merit Distribution">
            <DonutChart
              data={seed.meritCategoryDistribution}
              totalLabel="Total"
              valueFormatter={(value) => String(value)}
            />
          </Card>

          <Card title="Regeneration & versioning">
            <p className="text-[13px] text-grey-600">
              A merit list can be generated any number of times as ranking conditions change. Each
              generation is versioned, comparable against the previous version through a rank-movement
              diff, and the superseded version is retained rather than replaced.
            </p>
            <div className="mt-3 flex flex-wrap gap-2">
              <Button variant="secondary" size="sm">
                <Eye className="size-3.5" />
                Compare versions
              </Button>
              <Button variant="secondary" size="sm">
                <Download className="size-3.5" />
                Download (watermarked)
              </Button>
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}
